<a href="https://colab.research.google.com/github/sneharanig06/CDD-LAB-2/blob/main/4NI25CS196_EXP_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Welcome to Data Analytics and Visualization")

Welcome to Data Analytics and Visualization


In [ ]:
import numpy as np
marks = np.array([78,85,92,67,88])
print("Marks:", marks)
print("Type:",type(marks))

Marks: [78 85 92 67 88]
Type: <class 'numpy.ndarray'>


In [ ]:
print("Number of dimensions:", marks.ndim)
print("shape:",marks.shape)
print("Number of elements:",marks.size)

Number of dimensions: 1
shape: (5,)
Number of elements: 5


In [ ]:
marks=np.array([78,90,87,65])
print("original:",marks)
print("Add 5:",marks+5)
print("Multiply by 2:",marks*2)
print("Divide by 2:",marks/2)
print("square:",marks**2)

original: [78 90 87 65]
Add 5: [83 95 92 70]
Multiply by 2: [156 180 174 130]
Divide by 2: [39.  45.  43.5 32.5]
square: [6084 8100 7569 4225]


In [ ]:
print("sum:",marks.sum())
print("Mean:",marks.mean())
print("Maximum:",marks.max())
print("Minimum:",marks.min())

sum: 320
Mean: 80.0
Maximum: 90
Minimum: 65


In [ ]:
print("First mark:",marks[0])
print("Second mark:",marks[1])
print("Last mark:",marks[-1])

First mark: 78
Second mark: 90
Last mark: 65


In [ ]:
print("Index 1 to 3:",marks[1:4])
print("First three:",marks[:3])
print("From index 2:",marks[2::])
print("Every second element:",marks[::2])

Index 1 to 3: [90 87 65]
First three: [78 90 87]
From index 2: [87 65]
Every second element: [78 87]


In [ ]:
student_marks=np.array([
    [78,85,92],
    [67,88,76],
    [90,95,89],
])
print(student_marks)
print("shape:",student_marks.shape)

[[78 85 92]
 [67 88 76]
 [90 95 89]]
shape: (3, 3)


In [ ]:
print("Mean of all values:",student_marks.mean())
print("Column-wise mean:",student_marks.mean(axis=0))
print("row-wise mean:",student_marks.mean(axis=1))

Mean of all values: 84.44444444444444
Column-wise mean: [78.33333333 89.33333333 85.66666667]
row-wise mean: [85.         77.         91.33333333]


In [ ]:
import pandas as pd
data={
    "name":["anu","rahul","Kiran","Priya"],
    "branch":["CSE","AIML","CSE","AIML"],
    "Marks":[85,91,76,88]
}
df = pd.DataFrame(data)
df

,name,branch,Marks
0,anu,CSE,85
1,rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
print("shape:",df.shape)
print("\nColumns:")
print(df.columns)

shape: (4, 3)

Columns:
Index(['name', 'branch', 'Marks'], dtype='object')


In [ ]:
df.head()

,name,branch,Marks
0,anu,CSE,85
1,rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
df.tail()

,name,branch,Marks
0,anu,CSE,85
1,rahul,AIML,91
2,Kiran,CSE,76
3,Priya,AIML,88


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    4 non-null      object
 1   branch  4 non-null      object
 2   Marks   4 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [ ]:
df.describe()


,Marks
count,4.000000
mean,85.000000
std,6.480741
min,76.000000
25%,82.750000
50%,86.500000
75%,88.750000
max,91.000000


In [ ]:
print("Marks Column:")
print(df["Marks"])

Marks Column:
0    85
1    91
2    76
3    88
Name: Marks, dtype: int64


In [ ]:
print("Branch and Marks:")
print(df[["branch" , "Marks"]])

Branch and Marks:
  branch  Marks
0    CSE     85
1   AIML     91
2    CSE     76
3   AIML     88


In [ ]:
print("first row:")
print(df.iloc[0])
print("\nsecond row:")
print(df.iloc[1])
print("\nfirst three row:")
print(df.iloc[0:3])

first row:
name      anu
branch    CSE
Marks      85
Name: 0, dtype: object

second row:
name      rahul
branch     AIML
Marks        91
Name: 1, dtype: object

first three row:
    name branch  Marks
0    anu    CSE     85
1  rahul   AIML     91
2  Kiran    CSE     76


In [ ]:
print("first two rows and first two columns:")
print(df.iloc[0:2 ,2:0])

first two rows and first two columns:
Empty DataFrame
Columns: []
Index: [0, 1]


In [ ]:
print("First three rows:")
display(df.iloc[0:3])


print("Rows 1 to 3, Name and Marks:")
print(df.iloc[1:4,0:3])

First three rows:


,name,branch,Marks
0,anu,CSE,85
1,rahul,AIML,91
2,Kiran,CSE,76


Rows 1 to 3, Name and Marks:
    name branch  Marks
1  rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88


In [ ]:
high_scorers=df[df["Marks"]>90]
high_scorers

,name,branch,Marks
1,rahul,AIML,91


In [ ]:
print("students from CSE:")
display(df[df["branch"]=="CSE"])


print("Students scoring 80 and above:")
print(df[df["Marks"]>=85])

students from CSE:


,name,branch,Marks
0,anu,CSE,85
2,Kiran,CSE,76


Students scoring 80 and above:
    name branch  Marks
0    anu    CSE     85
1  rahul   AIML     91
3  Priya   AIML     88


In [ ]:
data={
    "name":["Asha","Bharat","Chetan","Priya"],
    "branch":["CSE","AIML","CSE","AIML"],
    "Marks":[85,91,76,88],
    "Attendance":[89,67,55,43]
}
students = pd.DataFrame(data)
students

,name,branch,Marks,Attendance
0,Asha,CSE,85,89
1,Bharat,AIML,91,67
2,Chetan,CSE,76,55
3,Priya,AIML,88,43


In [ ]:
print("Branch and Marks:")
print(df[["branch" , "Marks"]])

Branch and Marks:
  branch  Marks
0    CSE     85
1   AIML     91
2    CSE     76
3   AIML     88


In [ ]:
high_scorers=df[df["Marks"]>80]
high_scorers

,name,branch,Marks
0,anu,CSE,85
1,rahul,AIML,91
3,Priya,AIML,88


In [ ]:
attendance = students[students["Attendance"]>85]
attendance


,name,branch,Marks,Attendance
0,Asha,CSE,85,89


In [ ]:
print("First three rows:")
display(students.iloc[0:3])


First three rows:


,name,branch,Marks,Attendance
0,Asha,CSE,85,89
1,Bharat,AIML,91,67
2,Chetan,CSE,76,55


In [ ]:
print(students["Marks"].mean())

85.0


In [ ]:
print("maximum:",students["Marks"].max())

maximum: 91


In [ ]:
display(students[students["branch"]=="CSE"])

,name,branch,Marks,Attendance
0,Asha,CSE,85,89
2,Chetan,CSE,76,55


In [ ]:
print("Students scored 80 and have attendance above 85:")
display(students[(students["Marks"]>=80)&(students["Attendance"]>85)])

Students scored 80 and have attendance above 85:


,name,branch,Marks,Attendance
0,Asha,CSE,85,89
